ok-su-su/iOS

Projects/Share/Designsystem/Sources/SSBadges.swift
|View|View|
|:-:|:-:|
|![스크린샷 2024-04-15 오후 9 50 02](https://github.com/ok-su-su/iOS/assets/103064352/287b9824-1c26-4c08-9823-38637d3033c9)|![스크린샷 2024-04-15 오후 9 50 02](https://github.com/ok-su-su/iOS/assets/103064352/eba30dbb-d6bb-44ec-ac12-80cb46fe0955)|
N/A
N/A
close: #32
=> [Feature] Badge 기능 구현

Projects/App/Sources/ContentView.swift, Projects/Share/Designsystem/Sources/SSBadges.swift, Projects/Share/Designsystem/Sources/SSFont.swift, Projects/Share/Designsystem/Sources/SSTypoModifier.swift, Projects/Share/SSAlert/Sources/KeepSources.swift, Projects/Share/SSAlert/Sources/MessageAlert.swift
|View|View|
|:-:|:-:|
|![Simulator Screenshot - iPhone 15 Plus - 2024-04-17 at 12 14 42](https://github.com/ok-su-su/iOS/assets/103064352/6f6aa168-8dea-41ac-9a92-ae6012187adb)|![Simulator Screenshot - iPhone 15 Plus - 2024-04-17 at 12 14 42](https://github.com/ok-su-su/iOS/assets/103064352/fb8ab2bf-c30a-457d-a51a-d89d894290ff)|
N/A
close: #34
close: #41
=> [Feature] SSalert Typo 수정, SSFont 에 Text 추가 

Projects/App/Sources/Views/ContentView.swift, Projects/App/Sources/Views/InventoryView.swift, Projects/App/Sources/Views/InventoryViewFeature.swift
|View|
|:-:|
| ![IMG_7311](https://github.com/ok-su-su/iOS/assets/23008224/dbe697e5-28b5-477b-9d09-302534a0db57) |
- 한가지 네이밍에 의논할 부분이 있습니다. 저번 저희 끼리 정의한 네이밍이 있긴 했지만 Cell 같은 경우 Reducer 네이밍을 어떻게 정의해야할지 궁금해서 한번 올려봅니다!! :) 
- 아 이부분은 구현하면서 의문점이 들긴 했었는데, State에서 Equatable 프로토콜을 채택하는 코드와 채택하지 않는 코드를 보았습니다. 무슨 차이점이 있는지 궁금했지만 명확한 답은 보지 못해서 혹시 다른분들은 어떻게 생각하시는지 답변을 여쭤보고 싶어 올려봅니다.
close: #49
=> feat: InventoryViewFeature 비즈니스 로직 추가

Makefile
|View|View|
|:-:|:-:|
|||
N/A
N/A
close: #67
=> [Project] MakeFile 수정

.swiftformat, Workspace.swift
N/A
N/A
N/A
N/A
close: #108
close: #
=> [bug] tuist가 build되지 않던 문제 해결 

Projects/Feature/Inventory/Sources/InventoryMainView/Helpers/InventoryAccountDetailHelper.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryAccount.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryAccountDetail.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryAccountDetailView.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryAccountView.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryDatePickerModalSheet.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryDatePickerModalSheetView.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryFilter.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryFilterView.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventorySortSheetView.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryView.swift, Projects/Feature/Inventory/Sources/InventoryMainView/InventoryViewFeature.swift, Projects/Feature/Inventory/Sources/InventoryRouterView/InventoryAccountDetailRouter.swift, Projects/Feature/Inventory/Sources/InventoryRouterView/InventoryAccountDetailRouterView.swift, Projects/Feature/Sent/Sources/Commons/WrappingHStack.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentPeopleFilterHelper.swift
|View|
|:-:|
| <img src="https://github.com/ok-su-su/iOS/assets/23008224/913831f7-a26f-4733-b1c6-aa98599973d6" width="200" height="400"/>   | 
close: #107 
close: #
=> [Feature] 받아요 장부 상세 필터 화면 UI 기능 구현

Projects/App/Sources/Views/ContentView.swift, Projects/Feature/Vote/Sources/EditMyVote/EditMyVote.swift, Projects/Feature/Vote/Sources/EditMyVote/EditMyVoteProperty.swift, Projects/Feature/Vote/Sources/EditMyVote/EditMyVoteView.swift, Projects/Feature/Vote/Sources/VoteDetail/MyVote/MyVoteDetail.swift, Projects/Feature/Vote/Sources/VoteDetail/MyVote/MyVoteDetailProperty.swift, Projects/Feature/Vote/Sources/VoteDetail/MyVote/MyVoteDetailView.swift, Projects/Feature/Vote/Sources/VoteMain/VoteMain.swift, Projects/Feature/Vote/Sources/VoteMain/VoteMainView.swift, Projects/Feature/Vote/Sources/VoteRouter/VotePathPublisher.swift, Projects/Feature/Vote/Sources/VoteRouter/VoteRouter.swift, Projects/Feature/Vote/Sources/VoteRouter/VoteRouterInitialPath.swift, Projects/Feature/Vote/Sources/VoteRouter/VoteRouterPath.swift, Projects/Feature/Vote/Sources/VoteRouter/VoteRouterView.swift, Projects/Feature/Vote/Sources/VoteSearch/VoteSearchView.swift, Projects/Share/Designsystem/Sources/HeaderViewFeature.swift
Navigation 고민
Navigation 어떻게 하면 잘할까 고민하다가 NavigationPathPublisher를 통한 최 상단의 SingleTone 객체를 통해 접근
```swift
final class VotePathPublisher {
static var shared: VotePathPublisher = .init()
private var publisher: PassthroughSubject<VoteRouterPath.State, Never> = .init()
func pathPublisher() -> AnyPublisher<VoteRouterPath.State, Never> {
return publisher.eraseToAnyPublisher()
}
func push(_ path: VoteRouterPath.State) {
publisher.send(path)
}
private init() {}
}
//Redcuer ... code ...
return  .publisher {
VotePathPublisher.shared
.pathPublisher()
.map { path in .pushPath(path) }
}
case let .pushPath(nextPath):
if nextPath == .dismiss(.init()) {
return .run { _ in
await dismiss()
}
}
state.path.append(nextPath)
return .none
//사용하는 쪽 코드 …
```
=> [Feature] VoteRouter 구현 및 Vote Edit 구현 

Projects/App/Project.swift, Projects/App/Resources/LaunchScreen.storyboard, Projects/App/Sources/Views/ContentView.swift, Projects/Feature/InventoryPreview/Project.swift, Projects/Feature/InventoryPreview/Resources/KeepResources.swift, Projects/Feature/InventoryPreview/Sources/InventoryPreview.swift, Projects/Feature/InventoryPreview/Sources/KeepSources.swift, Projects/Feature/InventoryPreview/Tests/InventoryPreviewTest.swift, Projects/Feature/Sent/Sources/CreateEnvelope/CreateEnvelopeRouter/CreateEnvelopeRouter.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilter.swift, Tuist/ProjectDescriptionHelpers/Target+Tempaltes.swift, Workspace.swift
N/A
LaunchStroyBoard.storyBoard가 아닌 -> LaunchStroyBoard로 해야함
N/A
close: #124
close: #
=> [Project] 테스트 플라이트 배포 

Projects/Share/Designsystem/Sources/SSFont.swift
N/A
|View|View|
|:-:|:-:|
|||
close: #
close: #140
=> [Bug] 시스템 폰트 사이즈에 따라서 글자 크기가 변하던 버그 해결

Projects/Feature/Sent/Sources/CommonViewAndReducers/CustomTextField/CustomTextField.swift, Projects/Feature/Sent/Sources/CommonViewAndReducers/CustomTextField/CustomTextFieldView.swift, Projects/Feature/Sent/Sources/Commons/CustomDateFormatter/CustomDateFormatter.swift, Projects/Feature/Sent/Sources/Commons/RequestParameters/SearchEnvelopeRequestParameter.swift, Projects/Feature/Sent/Sources/CreateEnvelope/CreateEnvelopeName/CreateEnvelopeNameNetwork.swift, Projects/Feature/Sent/Sources/CreateEnvelope/CreateEnvelopePrice/CreateEnvelopePriceView.swift, Projects/Feature/Sent/Sources/Envelope/Envelope.swift, Projects/Feature/Sent/Sources/Envelope/EnvelopeNetwork.swift, Projects/Feature/Sent/Sources/SearchView/SearchEnvelope.swift, Projects/Feature/Sent/Sources/SearchView/SearchViewHelper.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilter.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilterNetwork.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilterView.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentPeopleFilterHelper.swift, Projects/Feature/Sent/Sources/SentMainView/SearchEnvelopeResponseDTO.swift, Projects/Feature/Sent/Sources/SentMainView/SentMain.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainNetwork.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift, Projects/Share/SSLayout/Sources/SliderValue.swift
|View|View|
|:-:|:-:|
|||
N/A
close: #149
close: #
=> [Feature] Sent Main화면 Filter 기능 구현

Projects/Feature/SSSearch/Sources/SSSearchProperty.swift, Projects/Feature/SSSearch/Sources/SSSearchReducer.swift, Projects/Feature/Sent/Sources/Commons/CustomNumberFormatter/NumberFormatter.swift, Projects/Feature/Sent/Sources/Commons/RequestBody/CreateEnvelopeRequestBody.swift, Projects/Feature/Sent/Sources/Commons/SharedContainer/CreateEnvelopeRequestShared.swift, Projects/Feature/Sent/Sources/CreateEnvelope/CreateEnvelopeRouter/CreateEnvelopeNetwork.swift, Projects/Feature/Sent/Sources/Envelope/EnvelopeNetwork.swift, Projects/Feature/Sent/Sources/Envelope/EnvelopeProperty.swift, Projects/Feature/Sent/Sources/EnvelopePriceProgress/EnvelopePriceProgressProperty.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilter.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentPeopleFilterHelper.swift, Projects/Feature/Sent/Sources/SentMainView/FilterProperty.swift, Projects/Feature/Sent/Sources/SentMainView/SearchEnvelopeResponseDTO.swift, Projects/Feature/Sent/Sources/SentMainView/SentMain.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainNetwork.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearch.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearchPersistence.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryDetail/EnvelopeDetailProperty.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryList/SpecificEnvelopeHistoryList.swift, Projects/Share/SSLayout/Sources/SliderValue.swift, Projects/Share/SSToast/Sources/SSToastProperty.swift
|View|View|
|:-:|:-:|
|||
close: #
close: #169
=> [Bug] Int to int64 로 최대 금액 변경

Projects/Feature/Sent/Sources/Envelope/EnvelopeNetwork.swift, Projects/Feature/Sent/Sources/SentMainView/SentMain.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainNetwork.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryDetail/SpecificEnvelopeHistoryDetail.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryList/SpecificEnvelopeHistoryList.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryList/SpecificEnvelopeHistoryListView.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeSharedState/SpecificEnvelopeSharedState.swift, Projects/Share/SSToast/Sources/SSToastProperty.swift
N/A
N/A
N/A
close: #175 
close: #180
=> [Bug] 봉투 삭제 버그 수정 

Projects/App/Project.swift, Projects/Feature/SSSearch/Sources/SSSearchProperty.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearch.swift, Projects/Feature/Vote/Sources/VoteSearch/VoteSearchProperty.swift, Tuist/ProjectDescriptionHelpers/Target+Tempaltes.swift
|View|View|
|:-:|:-:|
|||
close: #
close: #177
=> [Project] 어플리케이션 이름 변경 

Projects/Feature/Sent/Sources/SentMainView/SentMain.swift
=> [Bug] 봉투가 정렬되지 않던 버그 수정 

Projects/App/Project.swift, Scripts/EditArchiveVersion.py
|View|View|
|:-:|:-:|
|||
close: #
close: #
=> [Deploy] 0.2.3 Test Flight 배포 

Projects/Core/SSPersistancy/Sources/SSUserDefaultsManager.swift, Projects/Feature/Sent/Sources/Commons/RequestParameters/SearchEnvelopeRequestParameter.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainNetwork.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearch.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearchNetwork.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearchPersistence.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearchView.swift
|View|View|
|:-:|:-:|
|||
close: #186 
close: #
=> [Bug] Sent Module 검색후 Navigation 및 검색어 저장이 되지 않던 문제 해결 

Projects/App/Sources/Views/ContentView.swift, Projects/Feature/MyPage/Project.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMain.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMainItemListCellView.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMainNetwork.swift, Projects/Feature/MyPage/Sources/MyPageMain/ProfileMainRouter.swift, Projects/Feature/MyPage/Sources/MyPageMain/ProfileMainView.swift, Projects/Feature/Onboarding/Sources/OnboardingLogin/OnboardingLogin.swift, Projects/Feature/Onboarding/Sources/OnboardingLogin/OnboardingLoginView.swift, Projects/Share/Designsystem/Sources/SSNotificationName.swift
|View|View|
|:-:|:-:|
|||
close: #194
close: #
=> [Feature] MyPage FeedBack 및 개인정보 처리 방침 화면 연결 , logout 회원 탈퇴 기능 구현 

Projects/App/Project.swift
|View|View|
|:-:|:-:|
|||
close: #211
close: #
=> [Feature]  0.3.0 배포 

Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift
|View|View|
|:-:|:-:|
|||
close: #221
=> [Bug] 토큰 변조시 방어 로직 추가 

Projects/App/Sources/Views/ContentView.swift, Projects/Feature/MyPage/Sources/MyPageBuilder/ProfileBuilder.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMain.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMainNetwork.swift, Projects/Feature/MyPage/Sources/MyPageMain/ProfileMainView.swift, Projects/Feature/Received/Sources/ReceivedBuilderView/ReceivedBuilderView.swift, Projects/Feature/SSLaunchScreen/Sources/LaunchScreenMain/LaunchScreenHelper.swift, Projects/Feature/Sent/Sources/SentBuilderView/SentBuilderView.swift, Projects/Feature/Statistics/Sources/StatisticsBuilder/StatisticsBuilderView.swift, Projects/Feature/Vote/Sources/VoteBuilder/VoteBuilder.swift
N/A
|View|View|
|:-:|:-:|
|![image](https://github.com/ok-su-su/iOS/assets/103064352/9ca7ff23-796b-4030-a878-2daf740f5e2b)||
close: #224
close: #
=> [Feature] 회원 탈퇴 기능 추가 

Projects/App/Project.swift, Projects/Core/SSInterceptor/Sources/RefreshTokenTargetType.swift, Projects/Core/SSInterceptor/Sources/SSTokenInterceptor.swift, Projects/Feature/Onboarding/Sources/OnboardingAdditional/OnBoardingAdditionalNetwork.swift, Projects/Feature/SSLaunchScreen/Sources/LaunchScreenMain/LaunchScreenHelper.swift, Projects/Feature/SSLaunchScreen/Sources/SSLaunchScreenBuilderView/SSLaunchScreenBuilderView.swift
|View|View|
|:-:|:-:|
|||
close: #251
close: #
=> [Feature] 0.3.1 버전 배포 

Projects/Feature/SSEditSingleSelectButton/Sources/SingleSelectButtonProperty.swift, Projects/Feature/SSEditSingleSelectButton/Sources/SingleSelectButtonReducer.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditReducer.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditView.swift
|View|View|
|:-:|:-:|
|||
close: #241
close: #
=> [Bug] 보낸 봉투 수정 방문 여부 버그 수정 

Projects/Feature/MyPage/Sources/MyPageEdit/MyPageEditView.swift, Projects/Feature/SSEditSingleSelectButton/Sources/SingleSelectButtonView.swift
|View|View|
|:-:|:-:|
|![image](https://github.com/ok-su-su/iOS/assets/103064352/a82c8e1e-373b-4ebc-adc1-9176aab0845b)|![image](https://github.com/ok-su-su/iOS/assets/103064352/1f44a984-de18-43b2-b296-cd444575a30c)|
close: #
close: #255
=> [Bug] 마이페이지 내정보 수정 디자인 시스템 버그 수정

Projects/Feature/MyPage/Sources/MyPageEdit/MyPageEditView.swift, Projects/Feature/MyPage/Sources/MyPageInformation/MyPageInformationView.swift, Projects/Feature/MyPage/Sources/MyPageMain/ProfileMainView.swift, Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopePrice/CreateEnvelopePrice.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopePrice/CreateEnvelopePriceView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopeRouter/CreateEnvelopeNetwork.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsGift/CreateEnvelopeAdditionalIsGift.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsGift/CreateEnvelopeAdditionalIsGiftView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalMemo/CreateEnvelopeAdditionalMemo.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalMemo/CreateEnvelopeAdditionalMemoView.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeDetail/SpecificEnvelopeDetailReducer.swift, Projects/Feature/Sent/Sources/Commons/SharedContainer/CreateEnvelopeRequestShared.swift, Projects/Feature/Sent/Sources/Commons/SharedContainer/CreateFriendRequestShared.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift, Projects/Feature/Statistics/Sources/StatisticsMain/StatisticsMainView.swift, Projects/Feature/Vote/Sources/VoteMain/VoteMainView.swift, Projects/Share/Designsystem/Sources/SSTabbar.swift
=> [Bug] TabBar DesignSytem에 맞게 수정 

Projects/App/Project.swift
|View|View|
|:-:|:-:|
|||
close: #267
=> [Project] 7월 11일 버전 TestFlight 배포 

Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopeName/CreateEnvelopeName.swift, Projects/Feature/Sent/Sources/Envelope/EnvelopeProperty.swift, Projects/Feature/Sent/Sources/Envelope/EnvelopeView.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryList/SpecificEnvelopeHistoryListView.swift, Projects/Share/Designsystem/Sources/SSBadges.swift
|View|View|
|:-:|:-:|
|||
close: #
close: #270
=> [Bug] 0.3.2 버그 수정 

Projects/Feature/Onboarding/Sources/AgreeToTermsAndConditions/AgreeToTermsAndConditionsView.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailFilter/LedgerDetailFilter.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailFilter/LedgerDetailFilterNetwork.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailFilter/LedgerDetailFilterView.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/EnvelopeViewForLedgerMain.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMain.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMainView.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailProperty.swift, Projects/Feature/Received/Sources/ReceivedMain/LedgerBoxView.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditView.swift, Projects/Feature/Sent/Sources/Commons/ResponseDTO/SearchFilterEnvelopeResponse.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilter.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilterNetwork.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentEnvelopeFilterView.swift, Projects/Feature/Sent/Sources/SentEnvelopeFilter/SentPeopleFilterHelper.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift, Projects/Feature/Sent/Sources/SpecificEnvelope/SpecificEnvelopeHistoryList/SpecificEnvelopeHistoryListView.swift, Projects/Share/Designsystem/Sources/SSBadges.swift, Projects/Share/SSLayout/Sources/SliderValue.swift, Projects/Share/SSLayout/Sources/SliderView.swift
|View|View|
|:-:|:-:|
|||
close: #272 
close: #
=> [Feature] Filter View 시작 및 종료 Handle Text 구현 

Projects/App/Project.swift
|View|View|
|:-:|:-:|
|||
close: #
close: #274
=> [Project] 0.3.3 버전 배포

Projects/Feature/Sent/Sources/Envelope/EnvelopeView.swift, Projects/Feature/Sent/Sources/EnvelopePriceProgress/EnvelopePriceProgressView.swift, Projects/Share/Designsystem/Sources/SSFont.swift, Projects/Share/Designsystem/Sources/SSTypoModifier.swift, Projects/Share/SSBottomSelectSheet/Sources/SSSelectableBottomSheetModifier.swift, Projects/Share/SSBottomSelectSheet/Sources/SSSelectableBottomSheetView.swift
|View|View|
|:-:|:-:|
|||
close: #276
close: #227
=> [Bug] 정렬바 디자인 상이, 바텀 시트 텍스트 간격 수정 

Projects/Feature/Onboarding/Sources/OnboardingAdditional/OnboardingAdditional.swift, Projects/Feature/Onboarding/Sources/OnboardingAdditional/OnboardingAdditionalProperty.swift, Projects/Feature/Onboarding/Sources/OnboardingAdditional/OnboardingAdditionalView.swift
|View|View|
|:-:|:-:|
|||
close: #279
close: #
=> [Bug] 회원 가입 성별 선택 해제

Projects/Core/SSPersistancy/Sources/SSOauthManager.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMain.swift, Projects/Feature/MyPage/Sources/MyPageMain/MyPageMainNetwork.swift, Projects/Feature/Onboarding/Sources/AgreeToTermsAndConditions/AgreeToTermsAndConditionsHelper.swift, Projects/Feature/Onboarding/Sources/AgreeToTermsAndConditions/AgreeToTermsAndConditionsView.swift, Projects/Feature/Onboarding/Sources/Commons/SharedObject/LoginType.swift, Projects/Feature/Onboarding/Sources/OnboardingAdditional/OnboardingAdditionalView.swift, Projects/Feature/Onboarding/Sources/OnboardingLogin/OnboardingLogin.swift, Projects/Feature/Onboarding/Sources/OnboardingLogin/OnboardingLoginView.swift, Projects/Feature/Onboarding/Sources/OnboardingRegisterName/OnboardingRegisterName.swift, Projects/Feature/Onboarding/Sources/OnboardingRegisterName/OnboardingRegisterNameView.swift, Projects/Feature/Onboarding/Sources/OnboardingVote/OnboardingVote.swift, Projects/Feature/Onboarding/Sources/OnboardingVote/OnboardingVoteHelper.swift, Projects/Feature/Onboarding/Sources/OnboardingVote/OnboardingVoteView.swift, Projects/Feature/Onboarding/Sources/TermsAndConditionDetail/TermsAndConditionDetailView.swift, Projects/Share/Designsystem/Sources/SSTextFieldWithTCA.swift, Projects/Share/Designsystem/Sources/SSTypoModifier.swift, Projects/Share/SSBottomSelectSheet/Sources/SSSelectableBottomSheetModifier.swift
|View|View|
|:-:|:-:|
|||
close: #278
close: #280
close: #281
close: #282
close: #238
close: #285
=> bug: name Regex 적용, textField error message 우측 정렬 

Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMainView.swift, Projects/Feature/Received/Sources/ReceivedFilter/ReceivedFilterView.swift, Projects/Feature/Received/Sources/ReceivedMain/LedgerBoxView.swift, Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift, Projects/Feature/Received/Sources/ReceivedMain/SortHelperProperty.swift, Projects/Feature/SSSearch/Sources/SSSearchView.swift
close: #289
close: #290
close: #291
close: #288
=> [Bug] 받아요쪽 버그 수정

Projects/Feature/Onboarding/Sources/OnboardingLogin/OnboardingLoginView.swift, Projects/Feature/Onboarding/Sources/OnboardingVote/OnboardingVoteView.swift
|View|View|
|:-:|:-:|
|||
close: #287
close: #
=> [Feature] onboarding animation 수정

Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMain.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMainView.swift, Projects/Feature/Received/Sources/ReceivedMain/ReceivedMain.swift, Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift, Projects/Feature/Received/Sources/ReceivedMain/SortHelperProperty.swift, Projects/Feature/Sent/Sources/SentMainView/SentMain.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift, Projects/Share/Designsystem/Sources/ScrollViewWithFilterItems.swift
|View|View|
|:-:|:-:|
|||
close: #293
close: #
=> [Feature] 필터 뷰와 Scroll View 새로고침 및 sticky header 구현 

Projects/App/Project.swift
|View|View|
|:-:|:-:|
|||
close: #
close: #296
=> [Project] 0.3.4 버전 배포 

.github/ISSUE_TEMPLATE/bugfix.md
=> [Feature]Issue template 수정 

Projects/App/Sources/App/AppDelegate.swift, Projects/Core/SSRegexManager/Sources/RegexPatternString.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerCategory/CreateLedgerCategory.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerCategory/CreateLedgerCategoryView.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerName/CreateLedgerNameView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopeEvent/CreateEnvelopeEventView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopeName/CreateEnvelopeNameView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalContact/CreateEnvelopeAdditionalContactView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsGift/CreateEnvelopeAdditionalIsGift.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsGift/CreateEnvelopeAdditionalIsGiftView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsVisitedEvent/CreateEnvelopeAdditionalIsVisitedEvent.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsVisitedEvent/CreateEnvelopeAdditionalIsVisitedEventProperty.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalIsVisitedEvent/CreateEnvelopeAdditionalIsVisitedEventView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalMemo/CreateEnvelopeAdditionalMemo.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalMemo/CreateEnvelopeAdditionalMemoView.swift
close: #304 
close: #303 
close: #305
=> [Bug] Place Holder 수정, Toast Area 수정, 장부 생성 custom name textField 토스트 추가 

Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift
=> [Bug] 받아요 장부 ui 비율 min height 116으로 설정

Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditView.swift
=> [Bug] 봉투 수정 background color 조정

Projects/Feature/Onboarding/Sources/OnboardingAdditional/OnBoardingAdditionalNetwork.swift, Projects/Feature/Onboarding/Sources/OnboardingRegisterName/OnboardingRegisterName.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerCategory/CreateLedgerCategoryView.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerName/CreateLedgerNameView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelopeAdditional/CreateEnvelopeAdditionalContact/CreateEnvelopeAdditionalContactView.swift, Projects/Feature/SSSearch/Sources/SSSearchView.swift, Projects/Feature/Sent/Sources/SentSerach/SentSearch.swift
close: #311
close: #312 
close: #313
=> [Feature] keyboard dismiss 동작 추가, 검색 뷰 오타 수정, TextField Height 값 고정 

Projects/Feature/Received/Sources/ReceivedFilter/ReceivedFilterView.swift, Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift
|View|View|View|
|:-:|:-:|:-:|
|![IMG_9683](https://github.com/user-attachments/assets/d2404d41-f2ef-4097-ae59-67a3173fa419)|![IMG_9684](https://github.com/user-attachments/assets/f41974bc-5970-4712-9d42-fbdab5d28ee2)|![IMG_9685](https://github.com/user-attachments/assets/ecbe206b-35da-4704-993f-7f217169aca3)|
close: #316
close: #315
=> [Bug] 보내요, 받아요 Empty States 레이아웃 수정, 받아요 필터 경조사 카테고리 클릭 안되는 버그 수정  

Projects/App/Project.swift, Projects/App/Resources/PrivacyInfo.xcprivacy, Projects/Feature/AppleLogin/Sources/LoginWithApple.swift, Projects/Feature/Onboarding/Sources/OnboardingRegisterName/OnboardingRegisterName.swift, Projects/Feature/Onboarding/Sources/OnboardingRegisterName/OnboardingRegisterNameView.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerDate/CreateLedgerDate.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerDate/CreateLedgerDateView.swift, Projects/Feature/Received/Sources/CreateLedger/CreateLedgerName/CreateLedgerNameView.swift, Projects/Feature/Received/Sources/CreateLedger/NextButtonView/NextButtonView.swift, Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMain.swift, Projects/Feature/Received/Sources/ReceivedMain/SortHelperProperty.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift, Projects/Share/Designsystem/Sources/SSLoadingView.swift, Projects/Share/Designsystem/Sources/SSTextField.swift, Projects/Share/Designsystem/Sources/ScrollViewWithFilterItems.swift, Projects/Share/SSBottomSelectSheet/Sources/SSDateBottomSheetModifier.swift, Projects/Share/SSBottomSelectSheet/Sources/SSDateSelectBottomSheet.swift, Tuist/ProjectDescriptionHelpers/Target+Tempaltes.swift
close: #319
close: #318
close: #321
=> [Project] 1.0.0 버전 배포, 간헐적으로 발생하던 ScrollView 버그 수정, Date Picker with Bottom View 생성  

Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift
=> [Bug] 받아요 필터/정렬 영역 하단 간격 + empty box radius 

Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailEdit/LedgerDetailEditView.swift, Projects/Feature/SSCreateEnvelope/Sources/CreateEnvelope/CreateEnvelopeName/CreateEnvelopeNameView.swift, Projects/Feature/SSEditSingleSelectButton/Sources/SingleSelectButtonView.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditHelper.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditReducer.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditView.swift, Projects/Share/Designsystem/Sources/SSButton.swift, Projects/Share/Designsystem/Sources/SSTextfieldButton.swift, Projects/Share/SSLayout/Sources/SliderView.swift
close: #325
close: #327
close: #328
close: #326
close: #249
=> [Feature] 봉투 상세 수정 DatePicker 연결 

Projects/App/Project.swift, Scripts/EditArchiveVersion.py
=> [Project] 빌드 버전 올리는 스크립트 수정, 배포 버전 수정

Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailMainView/LedgerDetailMainView.swift, Projects/Feature/Received/Sources/ReceivedMain/ReceivedMainView.swift, Projects/Feature/SSEnvelope/Sources/SpecificEnvelopeEdit/SpecificEnvelopeEditView.swift, Projects/Feature/Sent/Sources/SentMainView/SentMainView.swift, Projects/Share/Designsystem/Sources/SSLoadingView.swift, Projects/Share/Designsystem/Sources/ScrollViewWithFilterItems.swift
=> [Feature] TextField View 터치 영역 수정, Scroll And Header Filter isLoading And IsRefershable 제거 

Projects/Feature/Received/Sources/LedgerDetail/LedgerDetailEdit/LedgerDetailEditView.swift
=> [Bug] 받아요 Background Color 수정 
